/* Standalone super-admin route. Every write is re-authorized by the API. */
(function(){
  const esc = value => String(value ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  async function request(path, options){ const response = await apiFetch(path, options || {}); const data = await response.json().catch(() => ({})); if(!response.ok) throw new Error(data.error || 'Request failed.'); return data; }
  let users = [];
  function render(){
    const rows = users.map(user => `<tr><td>${esc(user.email)}<small style="display:block;opacity:.65">${esc(user.id)}</small></td><td>${esc(user.provider)}</td><td>${esc(user.created_at)}</td><td><span class="tag ${user.status === 'active' ? 'good' : 'alert'}">${esc(user.status)}</span></td><td>${(user.branches || []).map(b => `${esc(b.role)} · ${esc(b.branches?.name || b.branch_id)}`).join('<br>') || 'none'}</td><td><button class="btn ghost sm" data-user-action="${user.status === 'active' ? 'suspend' : 'activate'}" data-user-id="${user.id}">${user.status === 'active' ? 'Suspend' : 'Activate'}</button> <button class="btn ghost sm" data-user-action="reset" data-user-id="${user.id}">Reset</button> <button class="btn ghost sm" data-user-action="impersonate" data-user-id="${user.id}" data-user-email="${esc(user.email)}">Impersonate</button></td></tr>`).join('');
    document.getElementById('root').innerHTML = `<div style="max-width:1250px;margin:0 auto;padding:32px 20px"><div style="display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:24px"><div><p class="eyebrow">Restricted control plane</p><h1>Super Admin</h1><p class="sub">Identity, access, audit, and operational health.</p></div><a class="btn ghost" href="/">Back to dashboard</a></div><div class="grid kpi" style="margin-bottom:16px"><div class="card kpi"><h3>Registered users</h3><div class="big">${users.length}</div></div><div class="card kpi"><h3>Active users</h3><div class="big">${users.filter(u=>u.status==='active').length}</div></div><div class="card kpi"><h3>Suspended users</h3><div class="big">${users.filter(u=>u.status==='suspended').length}</div></div></div><div class="form-card" style="margin-bottom:16px"><div style="display:flex;gap:8px;align-items:center"><input id="admin-search" placeholder="Search email or user ID" style="flex:1"><button class="btn gold" id="admin-refresh">Refresh</button></div><div class="form-row" style="margin-top:12px"><input id="grant-user" placeholder="User ID"><input id="grant-branch" placeholder="Branch ID"><select id="grant-role"><option>viewer</option><option>auditor</option><option>accountant</option><option>branch_manager</option><option>finance_manager</option><option>owner</option><option>super_admin</option></select><button class="btn ghost" id="grant-access">Grant or update access</button></div></div><div class="form-card"><div class="section-head"><h2>User directory</h2><span class="tag neutral">${users.length} users</span></div><div class="table-wrap"><table><thead><tr><th>User</th><th>Provider</th><th>Registered</th><th>Status</th><th>Assigned branches</th><th>Actions</th></tr></thead><tbody>${rows || '<tr><td colspan="6">No users found.</td></tr>'}</tbody></table></div></div><div class="grid two-col" style="margin-top:16px"><div class="form-card"><div class="section-head"><h2>Audit log</h2><button class="btn ghost sm" id="admin-audit">Load</button></div><pre id="admin-audit-output" style="white-space:pre-wrap;max-height:360px;overflow:auto">Audit events are loaded on request.</pre></div><div class="form-card"><div class="section-head"><h2>System health</h2><button class="btn ghost sm" id="admin-health">Run check</button></div><pre id="admin-health-output" style="white-space:pre-wrap;max-height:360px;overflow:auto">Health checks are loaded on request.</pre></div></div></div>`;
    document.getElementById('admin-refresh').addEventListener('click', () => loadUsers(document.getElementById('admin-search').value));
    document.getElementById('admin-search').addEventListener('keydown', event => { if(event.key === 'Enter') loadUsers(event.target.value); });
    document.getElementById('grant-access').addEventListener('click', async () => { try { await request('/api/admin/users', {method:'POST',headers:JSONH,body:JSON.stringify({action:'grant',user_id:document.getElementById('grant-user').value,branch_id:document.getElementById('grant-branch').value,role:document.getElementById('grant-role').value})}); showToast('Access grant saved.', 'success'); await loadUsers(); } catch(e) { showToast(e.message, 'error'); } });
    document.querySelectorAll('[data-user-action]').forEach(button => button.addEventListener('click', async () => {
      const action = button.dataset.userAction; const payload = { user_id: button.dataset.userId, action, ...(action === 'activate' ? {status:'active'} : {}), ...(action === 'suspend' ? {status:'suspended'} : {}) };
      try {
        if(action === 'impersonate'){
          const result = await request('/api/admin/impersonate', {method:'POST',headers:JSONH,body:JSON.stringify({user_id:payload.user_id})});
          sessionStorage.setItem('happynet_impersonation', JSON.stringify({originalSession:getSession(),targetEmail:button.dataset.userEmail,impersonatedBy:getSession()?.user?.id}));
          if(!result.action_link) throw new Error('No impersonation handoff link was generated.');
          window.location.href = result.action_link;
          return;
        }
        const result = await request('/api/admin/users', {method:'POST',headers:JSONH,body:JSON.stringify(action === 'reset' ? {user_id:payload.user_id,action:'password_reset'} : {user_id:payload.user_id,action:'status',status:payload.status})}); showToast(result.action_link ? 'Reset link generated.' : 'User updated.', 'success'); await loadUsers();
      } catch(e) { showToast(e.message, 'error'); }
    }));
    document.getElementById('admin-audit').addEventListener('click', async () => { try { const data = await request('/api/audit?limit=200'); document.getElementById('admin-audit-output').textContent = JSON.stringify(data, null, 2); } catch(e) { showToast(e.message, 'error'); } });
    document.getElementById('admin-health').addEventListener('click', async () => { try { const data = await request('/api/system-health'); document.getElementById('admin-health-output').textContent = JSON.stringify(data, null, 2); } catch(e) { showToast(e.message, 'error'); } });
  }
  async function loadUsers(search=''){ try { const data = await request('/api/admin/users' + (search ? `?search=${encodeURIComponent(search)}` : '')); users = data.users || []; render(); } catch(e) { showToast(e.message, 'error'); window.location.replace('/'); } }
  window.startAdminApp = async function(){ await loadUsers(); };
})();
